spring.application.name=ogrenci_bilgi_yonetim_sistemi
spring.datasource.url=jdbc:postgresql://localhost:5432/bys
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username=postgres
spring.datasource.password=emirhan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key
jwt.secret=635266556A586E3272357538782F413F4428472B4B6250655368566D59713374

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emirhanproje74@gmail.com
spring.mail.password=bkkm gatm zyzo tkzx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000