spring.application.name=ogrenci_bilgi_yonetim_sistemi
spring.datasource.url=jdbc:postgresql://localhost:5432/bys
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username=postgres
spring.datasource.password=emirhan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# JWT Secret Key
jwt.secret=635266556A586E3272357538782F413F4428472B4B6250655368566D59713374