services:
  - type: web
    name: bys-backend-final
    runtime: image
    image:
      path: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d7tgivcm0tmc73cnqiu0-a/bys
      - key: SPRING_DATASOURCE_USERNAME
        value: emirhan
      - key: SPRING_DATASOURCE_PASSWORD
        value: WdPZg36uY61mJVwY2ATK7ukNfIPSaJoo
