services:
  - type: web
    name: bys-uygulama
    env: java
    region: frankfurt
    plan: free
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/*.jar
    rootDir: ogrenci-ders-secimi-ve-akademik-yonetim-sistemi-main
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d7tgivcm0tmc73cnqiu0-a/bys
      - key: SPRING_DATASOURCE_USERNAME
        value: emirhan
      - key: SPRING_DATASOURCE_PASSWORD
        value: WdPZg36uY61mJVwY2ATK7ukNfIPSaJoo
      - key: PORT
        value: 8080
